import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { fetchPublicAsset } from "../api/assetApi";
import IssueReportModal from "../components/IssueReportModal";

const STATUS_STYLES = {
  Operational: "bg-emerald-900/40 text-emerald-300 border-emerald-700",
  "Issue Reported": "bg-amber-900/40 text-amber-300 border-amber-700",
  "Under Inspection": "bg-sky-900/40 text-sky-300 border-sky-700",
  "Under Maintenance": "bg-violet-900/40 text-violet-300 border-violet-700",
  "Out of Service": "bg-red-900/40 text-red-300 border-red-700",
  Retired: "bg-gray-800 text-gray-400 border-gray-700",
};

// Route: /assets/public/:assetCode  (matches publicUrl generated by the backend)
export default function PublicAssetPage() {
  const { assetCode } = useParams();
  const [asset, setAsset] = useState(null);
  const [activity, setActivity] = useState([]);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);
  const [showReportModal, setShowReportModal] = useState(false);

  useEffect(() => {
    const load = async () => {
      try {
        const data = await fetchPublicAsset(assetCode);
        setAsset(data.asset);
        setActivity(data.recentActivity || []);
      } catch (err) {
        setNotFound(true);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [assetCode]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center text-gray-400">
        Loading asset...
      </div>
    );
  }

  if (notFound || !asset) {
    return (
      <div className="min-h-screen bg-gray-950 flex flex-col items-center justify-center text-gray-100 p-6">
        <h1 className="text-2xl font-bold mb-2">Asset Not Found</h1>
        <p className="text-sm text-gray-400 text-center max-w-sm">
          This QR code or link doesn't match any registered asset. Please check
          with your facility administrator.
        </p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100 flex justify-center p-6">
      <div className="w-full max-w-md">
        {asset.isRetired && (
          <div className="bg-gray-800 border border-gray-700 text-gray-300 text-xs font-semibold rounded-lg py-2 px-3 mb-4 text-center">
            This asset has been retired
          </div>
        )}

        <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6">
          <p className="text-xs text-gray-500 font-mono mb-1">
            {asset.assetCode}
          </p>
          <h1 className="text-xl font-bold mb-3">{asset.name}</h1>

          <span
            className={`inline-block text-xs px-2.5 py-1 rounded-full border mb-4 ${STATUS_STYLES[asset.status] || ""}`}
          >
            {asset.status}
          </span>

          <dl className="text-sm space-y-2 mb-5">
            <Row label="Category" value={asset.category} />
            <Row label="Location" value={asset.location} />
            <Row label="Condition" value={asset.condition} />
            <Row
              label="Last Service"
              value={
                asset.lastServiceDate
                  ? new Date(asset.lastServiceDate).toLocaleDateString()
                  : "—"
              }
            />
            <Row
              label="Next Service"
              value={
                asset.nextServiceDate
                  ? new Date(asset.nextServiceDate).toLocaleDateString()
                  : "—"
              }
            />
          </dl>

          {!asset.isRetired && (
            <button
              onClick={() => setShowReportModal(true)}
              className="w-full bg-gradient-to-r from-violet-600 to-teal-500 text-white font-bold py-3 rounded-lg hover:opacity-90 transition"
            >
              Report an Issue
            </button>
          )}

          {showReportModal && (
            <IssueReportModal
              assetCode={assetCode}
              onClose={() => setShowReportModal(false)}
            />
          )}

          {activity.length > 0 && (
            <div className="mt-6">
              <h3 className="text-sm font-semibold mb-2">Recent Activity</h3>
              <ul className="text-xs text-gray-400 space-y-1.5">
                {activity.map((a) => (
                  <li key={a._id}>
                    {a.action}{" "}
                    <span className="text-gray-600">
                      · {new Date(a.createdAt).toLocaleDateString()}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function Row({ label, value }) {
  return (
    <div className="flex justify-between">
      <dt className="text-gray-500">{label}</dt>
      <dd className="text-gray-200">{value}</dd>
    </div>
  );
}
